feat : Added-token-generation-and-create-room
AOSSIE-Org/Resonate-Backend pull request #16
Opened 2023-06-02 04:06 UTC by SimardeepSingh1450

Closes Issues : #9 and #12
Changes :

1. Added TokenGeneration Function, currently the token generation endpoint takes 2 inputs -> Room Name and Participant Name.
2. Added CreateRoom Function, currently this function takes 1 input -> Room Name
3. Added Controllers and Routes folders for a better folder structure.
4. Added 'livekit-server-sdk' and 'dotenv' as dependency.

2023-06-02 15:39 UTC, chandansgowda requested changes
1. Change the file names to follow CamelCase.
2. Add instructions for contributors on how to place thier API keys in env file.

2023-06-02 15:42 UTC, chandansgowda commented
Also, the PR just partially resolves the referenced issues since Firebase room data is not being created or deleted. Please change the description accordingly.

2023-06-03 04:18 UTC, chandansgowda approved these changes

2023-06-05 15:54 UTC, chandansgowda requested changes
I think it would be better to have CRUD operations related to LiveKit Room in one file rather than having a separate file for each function.

2023-06-05 15:55 UTC, jddeep requested changes

2023-06-05 15:55 UTC, jddeep commented on controllers/createRoom.js
> +    }
please do proper code formatting

2023-06-07 15:41 UTC, chandansgowda approved these changes
Looks good to me.

2023-06-07 16:05 UTC, jddeep approved these changes

2023-06-07 16:06 UTC, merged