Appwrite functions implemented
AOSSIE-Org/Resonate-Backend pull request #29
Opened 2023-07-15 13:31 UTC by Aarush-Acharya

An appwrite_cloud_functions folder is added containing the 4 Appwrite cloud functions required for resonate to attain its current functionality

2023-07-16 04:33 UTC, Aarush-Acharya commented
Hey @chandansgowda Please do review this PR

2023-07-16 08:40 UTC, chandansgowda requested changes
The following changes have to be made:-
1. Add .DS_Store to gitignore
2. Rename folders to follow snake case nomenclature
3. Update Readme files for each function
4. Lets not commit the appwrite.json file if its generated. If its created manually, lets use ENV variables for API keys, database ids etc

2023-07-16 08:40 UTC, chandansgowda commented on appwrite_cloud_functions/.DS_Store
Please add this file to gitignore

2023-07-16 08:40 UTC, chandansgowda commented on appwrite_cloud_functions/Send OTP/appwrite.json
Is this file generated by cloud functions? If yes, lets not have it here since it has API keys etc

2023-07-16 08:49 UTC, Aarush-Acharya commented on appwrite_cloud_functions/Send OTP/appwrite.json
Alright Understood, Apologies for the inconvenience

2023-07-16 08:50 UTC, Aarush-Acharya commented on appwrite_cloud_functions/.DS_Store
Alright would do so

2023-07-17 10:13 UTC, Aarush-Acharya commented on appwrite_cloud_functions/Send OTP/appwrite.json
Hey @chandansgowda it is created by cloud functions if you use the cli it builds it for you but yes the file is modified with the variables so in this case what is to be done

2023-07-18 17:00 UTC, Aarush-Acharya commented
All right thanks for the review, would do so for all the functions and would also add the appwrite.json to the Resonates google drive

2023-07-19 06:44 UTC, Aarush-Acharya commented
Hey @chandansgowda exception handling is done for cloud functions and also integrated in the frontend and uploaded the appwrite.json files for each function along with a folder representing each to AOSSIE.org Google Drive

2023-07-31 05:57 UTC, chandansgowda approved these changes

2023-08-01 09:53 UTC, jddeep approved these changes

2023-08-01 09:53 UTC, merged