issue#24:Updated_README.md
AOSSIE-Org/Resonate-Backend pull request #44
Opened 2023-09-06 09:39 UTC by gerceboss

I have updated the README.md file  according to the reference link  provided in the issue #24

2023-09-15 16:07 UTC, chandansgowda requested changes

2023-09-15 16:07 UTC, chandansgowda commented on README.md
> +### Deleting exitsing
Typo

2023-09-18 18:04 UTC, gerceboss commented on README.md
> +### Deleting existing
Corrected the typo

2023-09-18 18:06 UTC, gerceboss commented
@chandansgowda  I have corrected the typo, and committed the changes .
Can I get assigned some more "good first issues"?

2023-10-09 15:26 UTC, closed without merging